project_id = "ughbqtlxgfybawixlnir"

[functions.player-auth]
verify_jwt = false

[functions.manage-stripe-keys]
verify_jwt = false

[functions.create-ticket-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-affiliate-user]
verify_jwt = false

[functions.manual-payment-action]
verify_jwt = false
