import bcrypt from 'bcryptjs';
import { prisma } from '../config/database.js';
import {
  NotFoundError,
  BadRequestError,
  ConflictError,
} from '../utils/errors.js';
import * as audit from './audit.service.js';
import { buildCreateChanges, buildUpdateChanges, buildDeleteChanges } from '../utils/auditChanges.js';

const BCRYPT_ROUNDS = 12;
const AFFILIATE_FIELDS = ['name', 'type', 'phone', 'email', 'parent_affiliate_id', 'commission_percent', 'permission_profile_id', 'is_sales_paused', 'is_active'];

export async function getByCompany(companyId: string) {
  return prisma.affiliates.findMany({
    where: {
      company_id: companyId,
      is_active: true,
      deleted_at: null,
    },
    include: {
      parent: {
        select: {
          id: true,
          name: true,
          type: true,
          commission_percent: true,
        },
      },
      children: {
        where: { is_active: true, deleted_at: null },
        select: {
          id: true,
          name: true,
          type: true,
          commission_percent: true,
          is_sales_paused: true,
        },
      },
      permission_profile: true,
    },
    orderBy: { created_at: 'desc' },
  });
}

export async function getById(id: string) {
  const affiliate = await prisma.affiliates.findUnique({
    where: { id },
    include: {
      parent: {
        select: {
          id: true,
          name: true,
          type: true,
          commission_percent: true,
        },
      },
      children: {
        where: { is_active: true, deleted_at: null },
        select: {
          id: true,
          name: true,
          type: true,
          commission_percent: true,
          is_sales_paused: true,
          link_code: true,
        },
      },
      permission_profile: true,
      company: {
        select: { id: true, name: true, slug: true },
      },
    },
  });

  if (!affiliate) {
    throw new NotFoundError('Affiliate not found');
  }

  return affiliate;
}

export async function create(
  companyId: string,
  data: {
    name: string;
    type: 'manager' | 'cambista';
    phone?: string;
    email?: string;
    parent_affiliate_id?: string;
    commission_percent?: number;
    permission_profile_id?: string;
  },
  createdBy?: string,
) {
  if (!data.name) {
    throw new BadRequestError('Name is required');
  }

  // If cambista, must have a parent manager
  if (data.type === 'cambista' && !data.parent_affiliate_id) {
    throw new BadRequestError('Cambista must have a parent manager');
  }

  // Validate parent exists if provided
  if (data.parent_affiliate_id) {
    const parent = await prisma.affiliates.findUnique({
      where: { id: data.parent_affiliate_id },
    });
    if (!parent) {
      throw new NotFoundError('Parent affiliate not found');
    }
    if (parent.type !== 'manager') {
      throw new BadRequestError('Parent must be a manager');
    }
  }

  // link_code is auto-generated by a DB trigger, but we need to provide a placeholder
  // that the trigger will override, or handle it in application code
  const linkCode = `${data.type.substring(0, 3)}_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;

  const affiliate = await prisma.affiliates.create({
    data: {
      company_id: companyId,
      name: data.name,
      type: data.type,
      phone: data.phone || null,
      email: data.email || null,
      parent_affiliate_id: data.parent_affiliate_id || null,
      commission_percent: data.commission_percent ?? 0,
      permission_profile_id: data.permission_profile_id || null,
      link_code: linkCode,
      created_by: createdBy || null,
      is_active: true,
    },
    include: {
      parent: {
        select: { id: true, name: true, type: true },
      },
      permission_profile: true,
    },
  });

  await audit.log({
    companyId,
    userId: createdBy,
    action: 'AFFILIATE_CREATED',
    entityType: 'affiliate',
    entityId: affiliate.id,
    changesJson: buildCreateChanges(affiliate, AFFILIATE_FIELDS),
  });

  return affiliate;
}

export async function update(
  id: string,
  data: {
    name?: string;
    phone?: string;
    email?: string;
    commission_percent?: number;
    parent_affiliate_id?: string;
    permission_profile_id?: string;
  },
  userId?: string,
) {
  const affiliate = await prisma.affiliates.findUnique({ where: { id } });
  if (!affiliate) {
    throw new NotFoundError('Affiliate not found');
  }

  // Track commission rate changes
  if (
    data.commission_percent !== undefined &&
    Number(data.commission_percent) !== Number(affiliate.commission_percent)
  ) {
    await prisma.commission_rate_changes.create({
      data: {
        entity_type: 'affiliate',
        entity_id: id,
        field_changed: 'commission_percent',
        old_value: affiliate.commission_percent,
        new_value: data.commission_percent,
        company_id: affiliate.company_id,
      },
    });
  }

  const updated = await prisma.affiliates.update({
    where: { id },
    data: {
      ...(data.name !== undefined ? { name: data.name } : {}),
      ...(data.phone !== undefined ? { phone: data.phone || null } : {}),
      ...(data.email !== undefined ? { email: data.email || null } : {}),
      ...(data.commission_percent !== undefined
        ? { commission_percent: data.commission_percent }
        : {}),
      ...(data.parent_affiliate_id !== undefined
        ? { parent_affiliate_id: data.parent_affiliate_id || null }
        : {}),
      ...(data.permission_profile_id !== undefined
        ? { permission_profile_id: data.permission_profile_id || null }
        : {}),
      updated_at: new Date(),
    },
    include: {
      parent: {
        select: { id: true, name: true, type: true },
      },
      permission_profile: true,
    },
  });

  const changes = buildUpdateChanges(affiliate, updated, AFFILIATE_FIELDS);
  if (changes) {
    await audit.log({
      companyId: affiliate.company_id,
      userId,
      action: 'AFFILIATE_UPDATED',
      entityType: 'affiliate',
      entityId: id,
      changesJson: changes,
    });
  }

  return updated;
}

export async function deleteAffiliate(id: string, userId?: string) {
  const affiliate = await prisma.affiliates.findUnique({ where: { id } });
  if (!affiliate) {
    throw new NotFoundError('Affiliate not found');
  }

  const result = await prisma.affiliates.update({
    where: { id },
    data: {
      deleted_at: new Date(),
      is_active: false,
      updated_at: new Date(),
    },
  });

  await audit.log({
    companyId: affiliate.company_id,
    userId,
    action: 'AFFILIATE_DELETED',
    entityType: 'affiliate',
    entityId: id,
    changesJson: buildDeleteChanges(affiliate, AFFILIATE_FIELDS),
  });

  return result;
}

export async function togglePause(id: string, userId: string) {
  const affiliate = await prisma.affiliates.findUnique({ where: { id } });
  if (!affiliate) {
    throw new NotFoundError('Affiliate not found');
  }

  const newPausedState = !affiliate.is_sales_paused;

  const result = await prisma.affiliates.update({
    where: { id },
    data: {
      is_sales_paused: newPausedState,
      paused_at: newPausedState ? new Date() : null,
      paused_by: newPausedState ? userId : null,
      updated_at: new Date(),
    },
  });

  await audit.log({
    companyId: affiliate.company_id,
    userId,
    action: 'AFFILIATE_TOGGLED',
    entityType: 'affiliate',
    entityId: id,
    changesJson: { before: { is_sales_paused: affiliate.is_sales_paused }, after: { is_sales_paused: newPausedState } },
  });

  return result;
}

export async function getByLinkCode(code: string) {
  const affiliate = await prisma.affiliates.findUnique({
    where: { link_code: code },
    include: {
      company: {
        select: { id: true, name: true, slug: true },
      },
      parent: {
        select: { id: true, name: true, type: true, commission_percent: true },
      },
    },
  });

  if (!affiliate || !affiliate.is_active || affiliate.deleted_at) {
    throw new NotFoundError('Affiliate not found');
  }

  return affiliate;
}

export async function createUser(
  affiliateId: string,
  email: string,
  password: string,
  userId?: string,
) {
  if (!email || !password) {
    throw new BadRequestError('Email and password are required');
  }

  if (password.length < 6) {
    throw new BadRequestError('Password must be at least 6 characters');
  }

  const affiliate = await prisma.affiliates.findUnique({
    where: { id: affiliateId },
  });

  if (!affiliate) {
    throw new NotFoundError('Affiliate not found');
  }

  if (affiliate.user_id) {
    throw new ConflictError('Affiliate already has a user account');
  }

  const normalizedEmail = email.toLowerCase().trim();

  // Check if email is already in use
  const existingUser = await prisma.users.findUnique({
    where: { email: normalizedEmail },
  });

  if (existingUser) {
    throw new ConflictError('Email already registered');
  }

  const passwordHash = await bcrypt.hash(password, BCRYPT_ROUNDS);

  // Create user, user_role, and update affiliate in a transaction
  const result = await prisma.$transaction(async (tx) => {
    // Create user
    const user = await tx.users.create({
      data: {
        email: normalizedEmail,
        password_hash: passwordHash,
        email_confirmed: true,
      },
    });

    // Create user_role as COLABORADOR for the affiliate's company
    await tx.user_roles.create({
      data: {
        user_id: user.id,
        role: 'COLABORADOR',
        company_id: affiliate.company_id,
      },
    });

    // Update affiliate with user_id and email
    await tx.affiliates.update({
      where: { id: affiliateId },
      data: {
        user_id: user.id,
        email: normalizedEmail,
        updated_at: new Date(),
      },
    });

    return {
      success: true,
      user_id: user.id,
      message: 'User account created and linked to affiliate',
    };
  });

  await audit.log({
    companyId: affiliate.company_id,
    userId,
    action: 'AFFILIATE_USER_CREATED',
    entityType: 'affiliate',
    entityId: affiliateId,
    changesJson: { created: { email: normalizedEmail, affiliate_id: affiliateId } },
  });

  return result;
}
